%bcond_without tests
%bcond_without weak_deps

%global __os_install_post %(echo '%{__os_install_post}' | sed -e 's!/usr/lib[^[:space:]]*/brp-python-bytecompile[[:space:]].*$!!g')
%global __provides_exclude_from ^/opt/ros/kilted/.*$
%global __requires_exclude_from ^/opt/ros/kilted/.*$

%global __cmake_in_source_build 1

Name:           ros-kilted-ur-robot-driver
Version:        4.3.0
Release:        1%{?dist}%{?release_suffix}
Summary:        ROS ur_robot_driver package

License:        BSD-3-Clause
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-kilted-backward-ros
Requires:       ros-kilted-controller-manager
Requires:       ros-kilted-controller-manager-msgs
Requires:       ros-kilted-effort-controllers
Requires:       ros-kilted-force-torque-sensor-broadcaster
Requires:       ros-kilted-geometry-msgs
Requires:       ros-kilted-hardware-interface
Requires:       ros-kilted-joint-state-broadcaster
Requires:       ros-kilted-joint-state-publisher
Requires:       ros-kilted-joint-trajectory-controller
Requires:       ros-kilted-launch
Requires:       ros-kilted-launch-ros
Requires:       ros-kilted-pluginlib
Requires:       ros-kilted-pose-broadcaster
Requires:       ros-kilted-position-controllers
Requires:       ros-kilted-rclcpp
Requires:       ros-kilted-rclcpp-lifecycle
Requires:       ros-kilted-rclpy
Requires:       ros-kilted-robot-state-publisher
Requires:       ros-kilted-ros2-controllers-test-nodes
Requires:       ros-kilted-rviz2
Requires:       ros-kilted-std-msgs
Requires:       ros-kilted-std-srvs
Requires:       ros-kilted-tf2-geometry-msgs
Requires:       ros-kilted-ur-client-library
Requires:       ros-kilted-ur-controllers
Requires:       ros-kilted-ur-dashboard-msgs
Requires:       ros-kilted-ur-description
Requires:       ros-kilted-ur-msgs
Requires:       ros-kilted-urdf
Requires:       ros-kilted-velocity-controllers
Requires:       ros-kilted-xacro
Requires:       socat
Requires:       ros-kilted-ros-workspace
BuildRequires:  ros-kilted-ament-cmake
BuildRequires:  ros-kilted-ament-cmake-python
BuildRequires:  ros-kilted-backward-ros
BuildRequires:  ros-kilted-controller-manager
BuildRequires:  ros-kilted-controller-manager-msgs
BuildRequires:  ros-kilted-geometry-msgs
BuildRequires:  ros-kilted-hardware-interface
BuildRequires:  ros-kilted-pluginlib
BuildRequires:  ros-kilted-rclcpp
BuildRequires:  ros-kilted-rclcpp-lifecycle
BuildRequires:  ros-kilted-rclpy
BuildRequires:  ros-kilted-std-msgs
BuildRequires:  ros-kilted-std-srvs
BuildRequires:  ros-kilted-tf2-geometry-msgs
BuildRequires:  ros-kilted-ur-client-library
BuildRequires:  ros-kilted-ur-controllers
BuildRequires:  ros-kilted-ur-dashboard-msgs
BuildRequires:  ros-kilted-ur-description
BuildRequires:  ros-kilted-ur-msgs
BuildRequires:  ros-kilted-ros-workspace
Provides:       %{name}-devel = %{version}-%{release}
Provides:       %{name}-doc = %{version}-%{release}
Provides:       %{name}-runtime = %{version}-%{release}

%if 0%{?with_tests}
BuildRequires:  ros-kilted-launch-testing-ament-cmake
%endif

%description
The new driver for Universal Robots UR3, UR5 and UR10 robots with CB3
controllers and the e-series.

%prep
%autosetup -p1

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kilted/setup.sh" ]; then . "/opt/ros/kilted/setup.sh"; fi
mkdir -p .obj-%{_target_platform} && cd .obj-%{_target_platform}
%cmake3 \
    -UINCLUDE_INSTALL_DIR \
    -ULIB_INSTALL_DIR \
    -USYSCONF_INSTALL_DIR \
    -USHARE_INSTALL_PREFIX \
    -ULIB_SUFFIX \
    -DCMAKE_INSTALL_PREFIX="/opt/ros/kilted" \
    -DAMENT_PREFIX_PATH="/opt/ros/kilted" \
    -DCMAKE_PREFIX_PATH="/opt/ros/kilted" \
    -DSETUPTOOLS_DEB_LAYOUT=OFF \
%if !0%{?with_tests}
    -DBUILD_TESTING=OFF \
%endif
    ..

%make_build

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kilted/setup.sh" ]; then . "/opt/ros/kilted/setup.sh"; fi
%make_install -C .obj-%{_target_platform}

%if 0%{?with_tests}
%check
# Look for a Makefile target with a name indicating that it runs tests
TEST_TARGET=$(%__make -qp -C .obj-%{_target_platform} | sed "s/^\(test\|check\):.*/\\1/;t f;d;:f;q0")
if [ -n "$TEST_TARGET" ]; then
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kilted/setup.sh" ]; then . "/opt/ros/kilted/setup.sh"; fi
CTEST_OUTPUT_ON_FAILURE=1 \
    %make_build -C .obj-%{_target_platform} $TEST_TARGET || echo "RPM TESTS FAILED"
else echo "RPM TESTS SKIPPED"; fi
%endif

%files
/opt/ros/kilted

%changelog
* Tue Oct 14 2025 Felix Exner <feex@universal-robots.com> - 4.3.0-1
- Autogenerated by Bloom

* Tue Sep 16 2025 Felix Exner <feex@universal-robots.com> - 4.2.0-1
- Autogenerated by Bloom

* Tue Jul 29 2025 Felix Exner <feex@universal-robots.com> - 4.1.0-1
- Autogenerated by Bloom

* Mon Jun 16 2025 Felix Exner <feex@universal-robots.com> - 4.0.3-1
- Autogenerated by Bloom

* Fri Jun 13 2025 Felix Exner <feex@universal-robots.com> - 4.0.2-1
- Autogenerated by Bloom

* Wed May 28 2025 Felix Exner <feex@universal-robots.com> - 4.0.1-1
- Autogenerated by Bloom

* Tue May 20 2025 Felix Exner <feex@universal-robots.com> - 4.0.0-1
- Autogenerated by Bloom

* Wed Apr 23 2025 Felix Exner <feex@universal-robots.com> - 3.2.1-2
- Autogenerated by Bloom

* Fri Apr 11 2025 Felix Exner <feex@universal-robots.com> - 3.2.1-1
- Autogenerated by Bloom

* Fri Apr 11 2025 Felix Exner <feex@universal-robots.com> - 3.2.0-1
- Autogenerated by Bloom

* Mon Mar 17 2025 Felix Exner <feex@universal-robots.com> - 3.1.1-1
- Autogenerated by Bloom

* Wed Mar 05 2025 Felix Exner <feex@universal-robots.com> - 3.1.0-1
- Autogenerated by Bloom

* Thu Jan 23 2025 Felix Exner <feex@universal-robots.com> - 3.0.2-1
- Autogenerated by Bloom

* Thu Jan 02 2025 Felix Exner <feex@universal-robots.com> - 3.0.1-1
- Autogenerated by Bloom

* Wed Dec 18 2024 Felix Exner <feex@universal-robots.com> - 3.0.0-1
- Autogenerated by Bloom

* Tue Oct 29 2024 Felix Exner <exner@fzi.de> - 2.4.13-1
- Autogenerated by Bloom

* Mon Oct 14 2024 Felix Exner <exner@fzi.de> - 2.4.12-1
- Autogenerated by Bloom

* Fri Oct 11 2024 Felix Exner <exner@fzi.de> - 2.4.11-1
- Autogenerated by Bloom

* Thu Sep 12 2024 Felix Exner <exner@fzi.de> - 2.4.10-1
- Autogenerated by Bloom

* Sun Aug 11 2024 Denis Stogl <denis@stoglrobotics.de> - 2.4.9-1
- Autogenerated by Bloom

* Mon Jul 01 2024 Denis Stogl <denis@stoglrobotics.de> - 2.4.8-1
- Autogenerated by Bloom

* Thu Jun 20 2024 Denis Stogl <denis@stoglrobotics.de> - 2.4.7-1
- Autogenerated by Bloom

* Mon Jun 17 2024 Denis Stogl <denis@stoglrobotics.de> - 2.4.6-1
- Autogenerated by Bloom

* Sat May 18 2024 Denis Stogl <denis@stoglrobotics.de> - 2.4.5-1
- Autogenerated by Bloom

