%bcond_without tests
%bcond_without weak_deps

%global __os_install_post %(echo '%{__os_install_post}' | sed -e 's!/usr/lib[^[:space:]]*/brp-python-bytecompile[[:space:]].*$!!g')
%global __provides_exclude_from ^/opt/ros/iron/.*$
%global __requires_exclude_from ^/opt/ros/iron/.*$

Name:           ros-iron-ur-robot-driver
Version:        2.3.9
Release:        1%{?dist}%{?release_suffix}
Summary:        ROS ur_robot_driver package

License:        BSD-3-Clause
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-iron-backward-ros
Requires:       ros-iron-controller-manager
Requires:       ros-iron-controller-manager-msgs
Requires:       ros-iron-force-torque-sensor-broadcaster
Requires:       ros-iron-geometry-msgs
Requires:       ros-iron-hardware-interface
Requires:       ros-iron-joint-state-broadcaster
Requires:       ros-iron-joint-state-publisher
Requires:       ros-iron-joint-trajectory-controller
Requires:       ros-iron-launch
Requires:       ros-iron-launch-ros
Requires:       ros-iron-pluginlib
Requires:       ros-iron-position-controllers
Requires:       ros-iron-rclcpp
Requires:       ros-iron-rclcpp-lifecycle
Requires:       ros-iron-rclpy
Requires:       ros-iron-robot-state-publisher
Requires:       ros-iron-ros2-controllers-test-nodes
Requires:       ros-iron-rviz2
Requires:       ros-iron-std-msgs
Requires:       ros-iron-std-srvs
Requires:       ros-iron-tf2-geometry-msgs
Requires:       ros-iron-ur-client-library
Requires:       ros-iron-ur-controllers
Requires:       ros-iron-ur-dashboard-msgs
Requires:       ros-iron-ur-description
Requires:       ros-iron-ur-msgs
Requires:       ros-iron-urdf
Requires:       ros-iron-velocity-controllers
Requires:       ros-iron-xacro
Requires:       socat
Requires:       ros-iron-ros-workspace
BuildRequires:  ros-iron-ament-cmake
BuildRequires:  ros-iron-ament-cmake-python
BuildRequires:  ros-iron-backward-ros
BuildRequires:  ros-iron-controller-manager
BuildRequires:  ros-iron-controller-manager-msgs
BuildRequires:  ros-iron-geometry-msgs
BuildRequires:  ros-iron-hardware-interface
BuildRequires:  ros-iron-pluginlib
BuildRequires:  ros-iron-rclcpp
BuildRequires:  ros-iron-rclcpp-lifecycle
BuildRequires:  ros-iron-rclpy
BuildRequires:  ros-iron-std-msgs
BuildRequires:  ros-iron-std-srvs
BuildRequires:  ros-iron-tf2-geometry-msgs
BuildRequires:  ros-iron-ur-client-library
BuildRequires:  ros-iron-ur-controllers
BuildRequires:  ros-iron-ur-dashboard-msgs
BuildRequires:  ros-iron-ur-description
BuildRequires:  ros-iron-ur-msgs
BuildRequires:  ros-iron-ros-workspace
Provides:       %{name}-devel = %{version}-%{release}
Provides:       %{name}-doc = %{version}-%{release}
Provides:       %{name}-runtime = %{version}-%{release}

%if 0%{?with_tests}
BuildRequires:  ros-iron-launch-testing-ament-cmake
%endif

%description
The new driver for Universal Robots UR3, UR5 and UR10 robots with CB3
controllers and the e-series.

%prep
%autosetup -p1

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/iron/setup.sh" ]; then . "/opt/ros/iron/setup.sh"; fi
mkdir -p .obj-%{_target_platform} && cd .obj-%{_target_platform}
%cmake3 \
    -UINCLUDE_INSTALL_DIR \
    -ULIB_INSTALL_DIR \
    -USYSCONF_INSTALL_DIR \
    -USHARE_INSTALL_PREFIX \
    -ULIB_SUFFIX \
    -DCMAKE_INSTALL_PREFIX="/opt/ros/iron" \
    -DAMENT_PREFIX_PATH="/opt/ros/iron" \
    -DCMAKE_PREFIX_PATH="/opt/ros/iron" \
    -DSETUPTOOLS_DEB_LAYOUT=OFF \
%if !0%{?with_tests}
    -DBUILD_TESTING=OFF \
%endif
    ..

%make_build

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/iron/setup.sh" ]; then . "/opt/ros/iron/setup.sh"; fi
%make_install -C .obj-%{_target_platform}

%if 0%{?with_tests}
%check
# Look for a Makefile target with a name indicating that it runs tests
TEST_TARGET=$(%__make -qp -C .obj-%{_target_platform} | sed "s/^\(test\|check\):.*/\\1/;t f;d;:f;q0")
if [ -n "$TEST_TARGET" ]; then
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/iron/setup.sh" ]; then . "/opt/ros/iron/setup.sh"; fi
CTEST_OUTPUT_ON_FAILURE=1 \
    %make_build -C .obj-%{_target_platform} $TEST_TARGET || echo "RPM TESTS FAILED"
else echo "RPM TESTS SKIPPED"; fi
%endif

%files
/opt/ros/iron

%changelog
* Mon Jul 01 2024 Denis Stogl <denis@stoglrobotics.de> - 2.3.9-1
- Autogenerated by Bloom

* Mon Jun 17 2024 Denis Stogl <denis@stoglrobotics.de> - 2.3.8-1
- Autogenerated by Bloom

* Sat May 18 2024 Denis Stogl <denis@stoglrobotics.de> - 2.3.7-1
- Autogenerated by Bloom

