%bcond_without tests
%bcond_without weak_deps

%global __os_install_post %(echo '%{__os_install_post}' | sed -e 's!/usr/lib[^[:space:]]*/brp-python-bytecompile[[:space:]].*$!!g')
%global __provides_exclude_from ^/opt/ros/galactic/.*$
%global __requires_exclude_from ^/opt/ros/galactic/.*$

Name:           ros-galactic-ur-robot-driver
Version:        2.1.2
Release:        1%{?dist}%{?release_suffix}
Summary:        ROS ur_robot_driver package

License:        BSD-3-Clause
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-galactic-controller-manager
Requires:       ros-galactic-controller-manager-msgs
Requires:       ros-galactic-geometry-msgs
Requires:       ros-galactic-hardware-interface
Requires:       ros-galactic-pluginlib
Requires:       ros-galactic-rclcpp
Requires:       ros-galactic-rclcpp-lifecycle
Requires:       ros-galactic-rclpy
Requires:       ros-galactic-std-msgs
Requires:       ros-galactic-std-srvs
Requires:       ros-galactic-tf2-geometry-msgs
Requires:       ros-galactic-ur-bringup
Requires:       ros-galactic-ur-client-library
Requires:       ros-galactic-ur-controllers
Requires:       ros-galactic-ur-dashboard-msgs
Requires:       ros-galactic-ur-description
Requires:       ros-galactic-ur-msgs
Requires:       ros-galactic-ros-workspace
BuildRequires:  ros-galactic-ament-cmake
BuildRequires:  ros-galactic-ament-cmake-python
BuildRequires:  ros-galactic-controller-manager
BuildRequires:  ros-galactic-controller-manager-msgs
BuildRequires:  ros-galactic-geometry-msgs
BuildRequires:  ros-galactic-hardware-interface
BuildRequires:  ros-galactic-pluginlib
BuildRequires:  ros-galactic-rclcpp
BuildRequires:  ros-galactic-rclcpp-lifecycle
BuildRequires:  ros-galactic-rclpy
BuildRequires:  ros-galactic-std-msgs
BuildRequires:  ros-galactic-std-srvs
BuildRequires:  ros-galactic-tf2-geometry-msgs
BuildRequires:  ros-galactic-ur-bringup
BuildRequires:  ros-galactic-ur-client-library
BuildRequires:  ros-galactic-ur-controllers
BuildRequires:  ros-galactic-ur-dashboard-msgs
BuildRequires:  ros-galactic-ur-description
BuildRequires:  ros-galactic-ur-msgs
BuildRequires:  ros-galactic-ros-workspace
Provides:       %{name}-devel = %{version}-%{release}
Provides:       %{name}-doc = %{version}-%{release}
Provides:       %{name}-runtime = %{version}-%{release}

%if 0%{?with_tests}
BuildRequires:  ros-galactic-launch-testing-ament-cmake
%endif

%description
The new driver for Universal Robots UR3, UR5 and UR10 robots with CB3
controllers and the e-series.

%prep
%autosetup -p1

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/galactic/setup.sh" ]; then . "/opt/ros/galactic/setup.sh"; fi
mkdir -p .obj-%{_target_platform} && cd .obj-%{_target_platform}
%cmake3 \
    -UINCLUDE_INSTALL_DIR \
    -ULIB_INSTALL_DIR \
    -USYSCONF_INSTALL_DIR \
    -USHARE_INSTALL_PREFIX \
    -ULIB_SUFFIX \
    -DCMAKE_INSTALL_PREFIX="/opt/ros/galactic" \
    -DAMENT_PREFIX_PATH="/opt/ros/galactic" \
    -DCMAKE_PREFIX_PATH="/opt/ros/galactic" \
    -DSETUPTOOLS_DEB_LAYOUT=OFF \
%if !0%{?with_tests}
    -DBUILD_TESTING=OFF \
%endif
    ..

%make_build

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/galactic/setup.sh" ]; then . "/opt/ros/galactic/setup.sh"; fi
%make_install -C .obj-%{_target_platform}

%if 0%{?with_tests}
%check
# Look for a Makefile target with a name indicating that it runs tests
TEST_TARGET=$(%__make -qp -C .obj-%{_target_platform} | sed "s/^\(test\|check\):.*/\\1/;t f;d;:f;q0")
if [ -n "$TEST_TARGET" ]; then
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/galactic/setup.sh" ]; then . "/opt/ros/galactic/setup.sh"; fi
CTEST_OUTPUT_ON_FAILURE=1 \
    %make_build -C .obj-%{_target_platform} $TEST_TARGET || echo "RPM TESTS FAILED"
else echo "RPM TESTS SKIPPED"; fi
%endif

%files
/opt/ros/galactic

%changelog
* Mon Aug 01 2022 Denis Stogl <denis@stoglrobotics.de> - 2.1.2-1
- Autogenerated by Bloom

* Thu May 05 2022 Denis Stogl <denis@stoglrobotics.de> - 2.1.1-1
- Autogenerated by Bloom

* Tue May 03 2022 Denis Stogl <denis@stoglrobotics.de> - 2.1.0-1
- Autogenerated by Bloom

